stakwork/stakgraph

- ast/src/testing/react_ts/mod.rs
- lsp/src/language.rs
This PR implements the following changes:
- fixes python package file errors and the inclusion of unnecessary files (.txt files) 
- sorts typescript function nodes so the intented functions are always picked
> chore: fixed package file parsing for python and ts function parsing

- ast/src/lang/queries/react_ts.rs
- ast/src/testing/react_ts/components/NewPerson.tsx
- ast/src/testing/react_ts/mod.rs
- ast/src/testing/react_ts/package.json
Added support for styled components lib in the NewPerson.tsx component
> styled components in react_ts parser

- ast/src/lang/parse.rs
- ast/src/lang/queries/bash.rs
- ast/src/testing/mod.rs
- ast/src/testing/utils.rs
- lsp/src/client.rs
- lsp/src/language.rs
> cleaning up dead code and small fix

- Cargo.lock
- ast/Cargo.toml
- ast/src/lang/mod.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/java.rs
- ast/src/lang/queries/mod.rs
- ast/src/testing/java/.gitattributes
- ast/src/testing/java/.gitignore
- ast/src/testing/java/.mvn/wrapper/maven-wrapper.properties
- ast/src/testing/java/mvnw
- ast/src/testing/java/mvnw.cmd
- ast/src/testing/java/pom.xml
- ast/src/testing/java/src/main/java/graph/stakgraph/java/JavaApplication.java
- ast/src/testing/java/src/main/java/graph/stakgraph/java/controller/PersonController.java
- ast/src/testing/java/src/main/java/graph/stakgraph/java/model/Person.java
- ast/src/testing/java/src/main/java/graph/stakgraph/java/repository/PersonRepository.java
- ast/src/testing/java/src/main/resources/application.properties
- ast/src/testing/mod.rs
- lsp/src/language.rs
> Java Server and Tree-Sitter Queries

- ast/src/builder.rs
- ast/src/lang/graph.rs
- ast/src/lang/linker.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/mod.rs
- ast/src/testing/angular/mod.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/python/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/svelte/mod.rs
- ast/src/testing/swift/mod.rs
- ast/src/testing/test_backend.rs
- ast/src/testing/test_frontend.rs
https://community.sphinx.chat/bounty/4178
> changed Node from enum to struct

- ast/src/builder.rs
- ast/src/lang/graph.rs
- ast/src/lang/graph_trait.rs
- ast/src/lang/linker.rs
- ast/src/lang/mod.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/go.rs
- ast/src/lang/queries/kotlin.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/python.rs
- ast/src/lang/queries/react.rs
- ast/src/lang/queries/ruby.rs
- ast/src/lang/queries/rust.rs
- ast/src/lang/queries/svelte.rs
- ast/src/lang/queries/swift.rs
- ast/src/repo.rs
- ast/src/testing/test_backend.rs
- ast/src/testing/test_frontend.rs
- ast/src/utils.rs
Referenceing : https://github.com/stakwork/stakgraph/pull/31/files#pullrequestreview-2738458784
And the the two critical methods `find_node` and `find_nodes` : #38 
@Evanfeenstra, is this a good base?
> refactor to graph trait

- ast/src/lang/graph.rs
- ast/src/lang/graph_trait.rs
- ast/src/lang/mod.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/go.rs
- ast/src/lang/queries/kotlin.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/python.rs
- ast/src/lang/queries/react.rs
- ast/src/lang/queries/ruby.rs
- ast/src/lang/queries/svelte.rs
- ast/src/lang/queries/swift.rs
> Abstacting Graph Traits

- ast/src/lang/graph.rs
- ast/src/lang/graph_trait.rs
- ast/src/lang/mod.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/ruby.rs
> converting the `parse.rs` file to be Graph Trait compatible

- .devcontainer/devcontainer.json
Publish updated LSP image
postCreateCommand cargo test run successfully on codespaces
> Stakgraph LSP Docker image

- ast/src/lang/queries/rails_routes.rs
- ast/src/testing/ruby/mod.rs
Fixes https://github.com/stakwork/stakgraph/issues/61
> chore: fix member issue

- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/graph.rs
- ast/src/testing/angular/mod.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/mod.rs
- ast/src/testing/python/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/react/src/App.tsx
- ast/src/testing/react/yarn.lock
- ast/src/testing/ruby/mod.rs
- ast/src/testing/svelte/mod.rs
- ast/src/testing/swift/mod.rs
- ast/src/testing/test_backend.rs
- ast/src/testing/test_frontend.rs
-[X] Make front-end and backend test generic
-[ ] Make individual test generic
-[ ] Make Linker Generic
-[ ] Test BtreeMapGraph
> Make remaining code sections generic

- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/graph.rs
- ast/src/lang/linker.rs
- ast/src/repo.rs
> made linker.rs generic and refactored graphs

- ast/src/builder.rs
- ast/src/lang/asg.rs
- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/go.rs
- ast/src/lang/queries/kotlin.rs
- ast/src/lang/queries/python.rs
- ast/src/lang/queries/react.rs
- ast/src/lang/queries/ruby.rs
- ast/src/lang/queries/svelte.rs
- ast/src/lang/queries/swift.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/graphs.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/ruby/mod.rs
- ast/src/testing/swift/mod.rs
- ast/src/utils.rs
> Fix: Adding remaining languages to the test

- ast/src/lang/queries/ruby.rs
- ast/src/testing/ruby/mod.rs
> fix ruby class queries

- Cargo.lock
- ast/Cargo.toml
- ast/src/builder.rs
- ast/src/lang/graphs/mod.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/testing/neo4j_graph.rs
> Implement the Graph Trait for Neo4jGraph

- ast/src/lang/parse.rs
> Import names to constant

- ast/src/builder.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/consts.rs
- ast/src/lang/queries/ruby.rs
- ast/src/testing/ruby/mod.rs
> Adding ruby Class association edge.

- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/mod.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/lang/linker.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/ruby.rs
- ast/src/testing/angular/mod.rs
- ast/src/testing/graphs/graph_updates.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/ruby/mod.rs
This PR Attends to #139 
and provides the necessary tests for #134
> removed CallsMeta and added ruby class call test

- ast/src/lang/parse.rs
- ast/src/lang/queries/react.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/react/src/App.tsx
- ast/src/testing/react/src/api.ts
> Getting all react top level and exported Variables

- ast/src/lang/parse.rs
- ast/src/lang/queries/angular.rs
- ast/src/lang/queries/kotlin.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/python.rs
- ast/src/lang/queries/rust.rs
- ast/src/lang/queries/typescript.rs
- ast/src/testing/angular/mod.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/mod.rs
- ast/src/testing/python/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/rust/src/main.rs
- ast/src/testing/rust_test.rs
- ast/src/testing/typescript/mod.rs
> Variables and Import Edges

- ast/src/lang/parse.rs
- ast/src/lang/queries/java.rs
- ast/src/lang/queries/ruby.rs
- ast/src/lang/queries/swift.rs
- ast/src/testing/java/mod.rs
- ast/src/testing/java/src/main/java/graph/stakgraph/java/controller/PersonController.java
- ast/src/testing/mod.rs
- ast/src/testing/ruby/mod.rs
- ast/src/testing/swift/SphinxTestApp/AppDelegate.swift
- ast/src/testing/swift/mod.rs
- treesitter/readme.md
> Adding Vars and Import Edges (non-lsp)

- .github/workflows/publish-standalone.yml
Updated workflow to support multiple architecture docker file.
> multi platform workflow

- ast/src/lang/queries/rust.rs
- standalone/docker-compose.yaml
pulls docker image for standalone online.
> docker image is pulled online for standalone

- ast/src/builder.rs
- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/graph.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/typescript.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/graphs/compare_graphs.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/typescript/mod.rs
- lsp/src/language.rs
Making LSP consistent for ArrayGraph and BtreeMap  in TS. Addressing #162
> Fixing unstable Typescript LSP

- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/graph_ops.rs
- standalone/src/handlers.rs
Some edges were missing from the upload of the Neo4j Graph
This PR attends to: https://github.com/stakwork/stakgraph/issues/174
> fix: missing edge on upload

- ast/src/builder.rs
- ast/src/lang/parse.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/ruby.rs
- ast/src/testing/ruby/mod.rs
> Feat : Class calls DM

- ast/src/builder.rs
- ast/src/repo.rs
- ast/src/testing/java/mod.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/test_frontend.rs
- lsp/src/language.rs
> Adding files to Kotlin Implementation

- ast/src/lang/queries/kotlin.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/react/src/components/People.tsx
- ast/src/testing/react/src/components/Person.tsx
addressing #240 
- Testing react use*tore; specific test
> kotlin operands

- ast/src/builder/core.rs
- ast/src/builder/utils.rs
- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/mod.rs
- ast/src/lang/mod.rs
- ast/src/lang/queries/angular.rs
- ast/src/lang/queries/mod.rs
- ast/src/testing/angular/mod.rs
- ast/src/testing/angular/src/app/app.component.html
- ast/src/testing/ruby/mod.rs
Created nested pages for Angular. 
Page[HTML] - Renders -> Page[HTML]
> Angular nested pages

- standalone/static/app.js
- standalone/static/styles.css
This PR adds real-time progress visualization during repository ingestion to improve user experience:
- Shows current step and total steps (e.g., "Step 3/15: process_and_add_files")
- Displays percentage completion with visual progress bar
- Implements text-based progress indicator using equals signs `[====    ]`
- Maintains consistent dark theme styling
The implementation uses Server-Sent Events (SSE) to stream progress updates from the backend to the frontend in real-time.
> Add real-time progress visualization for repository ingestion process

- .github/workflows/e2e-standalone.yml
- .github/workflows/e2e-test.yml
Fixing Wait rust server logic for github workflow
> fix: wait for rust server

- ast/src/lang/graphs/graph_ops.rs
- standalone/src/main.rs
> fix: panic if no neo4j

- ast/examples/ruby.rs
- ast/examples/url.rs
- ast/src/index.rs
- ast/src/lang/graphs/graph_ops.rs
- ast/src/repo.rs
- skill/src/main.rs
- standalone/src/handlers.rs
- standalone/src/types.rs
- standalone/tests/graph_consistency.rs
- standalone/tests/graph_updates.rs
Adding `use_lsp` to endpoint as a parameter. 
Addressing #298
> LSP to endpoint

- ast/src/builder/core.rs
- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/testing/cpp/mod.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/java/mod.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/python/mod.rs
- ast/src/testing/ruby/mod.rs
- ast/src/testing/rust_test.rs
- ast/src/testing/typescript/mod.rs
- standalone/src/handlers.rs
- standalone/tests/graph_updates.rs
Implementing Git pull or clone. To make sure repo is always up to date.
> Pull clone

- .github/workflows/e2e-test.yml
- ast/src/builder/core.rs
- ast/src/builder/utils.rs
- ast/src/index.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/lang/parse/collect.rs
- ast/src/lang/parse/format.rs
- ast/src/lang/queries/go.rs
- ast/src/lang/queries/react.rs
- ast/src/repo.rs
- ast/src/testing/angular/mod.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/java/mod.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/python/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/ruby/mod.rs
- ast/src/testing/rust_test.rs
- ast/src/testing/svelte/mod.rs
- ast/src/testing/swift/mod.rs
- ast/src/testing/typescript/mod.rs
- ast/src/utils.rs
- lsp/src/client.rs
- lsp/src/lib.rs
- standalone/tests/graph_consistency.rs
preserve the "root"s of files, and dont add again at the end
> Preserve roots

- ast/src/builder/core.rs
- ast/src/builder/utils.rs
- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/graph.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/lang/linker.rs
- ast/src/lang/parse/format.rs
- ast/src/repo.rs
- ast/src/testing/typescript/mod.rs
- lsp/src/language.rs
Affirm the language of the programming language before returning nodes
> Affirm Node language

- standalone/tests/graph_accuracy.rs
Makes sure when graph is processed it's still correct.
> Graph Accuracy Test

- ast/src/builder/core.rs
- ast/src/testing/svelte/mod.rs
- ast/src/testing/typescript/mod.rs
- lsp/src/language.rs
> Selective Parsing

- ast/src/lang/asg.rs
- ast/src/lang/call_finder.rs
- ast/src/lang/parse/format.rs
> Prevent self loops

- mcp/src/eval/route.ts
- mcp/src/tools/stagehand/utils.ts
- mcp/testing/test-console-logs-practical.js
Implements per-action console log isolation to resolve log accumulation issue. Adds action-sequence ID system with automatic memory management while maintaining full backward compatibility.
- Each `/evaluate` call generates unique action ID and returns it in response
- Console logs stored in both global array (compatibility) and action-specific Maps  
- Automatic cleanup with 1-hour TTL and 100-action LRU limits
- Enhanced `/console-logs` endpoint accepts optional `action_id` query parameter
- **POST /evaluate**: Now returns `action_id` field
- **GET /console-logs?action_id=xyz**: Returns action-specific logs
- **GET /console-logs**: Returns global logs (unchanged for backward compatibility)
- `src/tools/stagehand/utils.ts`: Action management system (+72 lines)
- `src/eval/route.ts`: …
> Implement action-sequence ID isolation for HTTP console logs

- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/lang/parse/format.rs
> fix:missing handler edges

- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/mod.rs
> clean up for btreemap

- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
> clear graph update

- ast/src/lang/graphs/neo4j_graph.rs
- standalone/tests/graph_updates.rs
Update Graph update. 
simuatated from the repo: https://github.com/fayekelmith/demo-repo
> chore: graph_update improvement

- mcp/src/graph/service.ts
> services error handling

- ast/src/lang/parse/format.rs
- ast/src/lang/queries/swift.rs
- ast/src/testing/nextjs/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/swift/mod.rs
- lsp/src/language.rs
Addressing #367 and adding swift tests
> Swift tests

- standalone/src/handlers.rs
- standalone/src/types.rs
> fix: updated return types for standalone endpoints

- standalone/tests/fulltest.rs
improving fulltest to be more comprehensive
> chore: update fulltest

- mcp/tests/app.js
- mcp/tests/hooks.js
- mcp/tests/playwright-generator.js
- mcp/tests/staktrak.js
- mcp/tests/style.css
The PR implements a comprehensive refactoring of the StakTrak test recording system with the following improvements:
1. Proper separation of concerns across files:
- Moved UI logic to app.js
- Enhanced hooks.js with specialized hooks for different functionalities
- Centralized test generation logic in playwright-generator.js
- Improved tracking and assertion handling in staktrak.js
2. Added better user feedback:
- Visual display of selected text
- Improved popup notifications
- Better error handling
3. Improved code quality:
- Removed duplicate logic
- Better organized functions and modules
- Added proper documentation
- Enhanced type definitions
This refactoring makes the codebase more maintainable, easier to extend, and provides a better developer experience. …
> Refactor StakTrak: Improve Code Organization and Separation of Concerns

- ast/src/lang/queries/python.rs
- ast/src/testing/python/mod.rs
- ast/src/testing/python/requirements.txt
updating python treesitter queries for libraries and it's tests
> fix: python libraries

- ast/src/lang/graphs/array_graph.rs
- ast/src/testing/go/mod.rs
- ast/src/testing/java/mod.rs
- ast/src/testing/kotlin/mod.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/ruby/mod.rs
- ast/src/testing/rust_test.rs
- ast/src/testing/swift/mod.rs
> fix: updating tests for accountability. 

- mcp/tests/hooks.js
- mcp/tests/playwright-generator.js
- mcp/tests/staktrak.js
**PR Description:**  
This PR refactors the StakTrak test recording system to improve code organization and maintainability:
- Centralizes all tracking data processing logic in `staktrak.js` and exposes it via `window.StakTrakUtils`.
- Removes duplicate data processing code from `hooks.js` and `playwright-generator.js`, ensuring all modules use the single source of truth from `staktrak.js`.
- Updates hooks and generator logic to call `StakTrakUtils.processTrackingData` for consistent and reliable data handling.
- Improves documentation and clarifies function responsibilities.
- No changes to user-facing features; all existing functionality is preserved.
> Refactor StakTrak: Centralize Data Processing and Remove Duplication

- ast/src/builder/core.rs
- ast/src/builder/progress.rs
- ast/src/repo.rs
Trimmed out fast steps in the graph building process.
> chore: trim out fast steps

- ast/src/lang/queries/react.rs
- ast/src/lang/queries/typescript.rs
- ast/src/testing/react/src/ComponentPatterns.tsx
- ast/src/testing/react/src/components/NewPerson.tsx
> fix: react return types

- standalone/static/app.js
Reset standalone UI after completion.
> fix: reset UI after completion

- mcp/src/eval/tests.ts
- mcp/tests/app.js
- mcp/tests/frame/frame.html
- mcp/tests/hooks.js
- mcp/tests/staktrak/dist/replay.js
- mcp/tests/staktrak/package.json
- mcp/tests/staktrak/src/replay.ts
- mcp/tests/staktrak/src/types.ts
- mcp/tests/style.css
This PR implements a new iframe test replay functionality that allows users to visually replay recorded test actions directly within the iframe. This feature provides a comprehensive way for users to visualize how their tests interact with the UI, enhancing debugging and validation capabilities.
1. **Action Execution System:** Built a robust system to execute recorded actions
- Created element selection with intelligent fallback mechanisms
- Implemented realistic event dispatching for authentic interactions
- Developed timing controls to properly sequence actions
2. **Tracking Data Processing:** Designed a flexible system for handling various data formats
- Created processing pipelines for click data and selectors
- Implemented fallback mechanisms for incomplete tracking data
- Added …
> Implement Iframe Test Replay with Improved Tracking and Visual Feedback

- ast/src/testing/nextjs/mod.rs
- ast/src/testing/rust_test.rs
> chore: more specific testing

- ast/src/builder/progress.rs
- ast/src/lang/graphs/graph_ops.rs
- standalone/src/handlers.rs
- standalone/static/app.js
- standalone/static/styles.css
- standalone/tests/graph_consistency.rs
- Accounted for the Graph upload steps (nodes and edges)
- Updated Graph UI to maintain stakGraph title all the time.
> fix: update processing steps and standalone ui

- ast/src/builder/core.rs
- ast/src/lang/queries/angular.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/react.rs
- ast/src/lang/queries/ruby.rs
- ast/src/testing/angular/mod.rs
- ast/src/testing/nextjs/app/items/page.tsx
- ast/src/testing/nextjs/app/page.tsx
- ast/src/testing/nextjs/app/person/page.tsx
- ast/src/testing/nextjs/mod.rs
Addressing #467 
The Goal is:
- Create Nextjs Pages as: 
- name: folder name
- file: full path
- body: relative path without `page.tsx`
Create Page - RENDERS ->  Functions (Components in the file). 
---
- Updated the implementation in Angular so that PAGE node and Render EDGE  addition accommodate a more language-agnostic implementation. 
- Update the tests for Angular. 
- Rebased to updated nextjs testing.
> Feat: nextjs pages

- ast/src/lang/queries/react.rs
- ast/src/testing/nextjs/mod.rs
Addressing #478 
- remove `tmp` from file path
- update the Page Node body to contain just the Nextjs Page route
> fix: update nextjs page body and file

- mcp/src/graph/routes.ts
- mcp/src/graph/service.ts
- mcp/src/graph/types.ts
- mcp/src/graph/utils.ts
Addressing #476 
Returning the container configuration for docker-compose.yaml files.
> feat: container service

- ast/src/lang/queries/react.rs
- ast/src/testing/nextjs/mod.rs
-  [X] expanded the Nextjs testing for Routes Pages and Render edge in to comprehensive test. 
-  [x] Get more specific tests in, for every node and edge.
> chore: more nextjs testing

- ast/src/testing/cpp/mod.rs
- ast/src/testing/nextjs/mod.rs
- nextjs
- cpp (structure and context)
> more nextjs specific testing

- .github/workflows/e2e-standalone.yml
- Cargo.lock
- ast/Cargo.toml
- ast/src/lang/embedding.rs
- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/lang/mod.rs
- mcp/testing/vector-search-response.json
- shared/Cargo.toml
- shared/src/error.rs
- standalone/src/handlers.rs
- standalone/src/main.rs
- standalone/src/types.rs
> feature: vector embedding with fastembed in rust

- ast/src/repo.rs
- standalone/src/handlers.rs
- standalone/static/app.js
- standalone/static/styles.css
--- 
---
action buttons on graph ingestion complete, commit input field and LSP button.
---
Closes #480
> chore: updating standalone UI

- ast/src/lang/graphs/graph_ops.rs
- standalone/src/handlers.rs
- standalone/src/main.rs
- standalone/src/types.rs
- standalone/src/utils.rs
Closes: https://github.com/stakwork/stakgraph/pull/524#issuecomment-3196371236
@Evanfeenstra please can you review this PR?
> fix: update /tests/uncovered response and params to be similar to repo2graph

- mcp/src/eval/tests.ts
Implemented the rename endpoint on Staktrak
> feat: rename endpoint to staktrak

- ast/src/builder/core.rs
- ast/src/lang/asg.rs
- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/graph.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/lang/mod.rs
- ast/src/lang/parse/collect.rs
- ast/src/lang/parse/format.rs
- ast/src/lang/queries/consts.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/react.rs
- ast/src/testing/nextjs/app/test/alias.vitest.test.ts
- ast/src/testing/nextjs/app/test/component.spec.tsx
- ast/src/testing/nextjs/app/test/e2e.cy.test.ts
- ast/src/testing/nextjs/app/test/e2e.playwright.each.test.ts
- ast/src/testing/nextjs/app/test/integration.api.spec.ts
- ast/src/testing/nextjs/app/test/mixed.nested.test.ts
- ast/src/testing/nextjs/app/test/param.each.test.ts
- ast/src/testing/nextjs/app/test/puppeteer.flow.test.ts
- ast/src/testing/nextjs/app/test/unit.component.test.tsx
- ast/src/testing/nextjs/mod.rs
> enhance: tests capture nextjs

- ast/src/builder/core.rs
- ast/src/lang/asg.rs
- ast/src/lang/graphs/array_graph.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/lang/graphs/graph.rs
- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/graphs/mod.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- ast/src/lang/graphs/utils.rs
- ast/src/lang/linker.rs
- ast/src/lang/mod.rs
- ast/src/lang/parse/collect.rs
- ast/src/lang/parse/format.rs
- ast/src/lang/queries/consts.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/react.rs
- ast/src/testing/nextjs/app/test/alias.vitest.test.ts
- ast/src/testing/nextjs/app/test/component.spec.tsx
- ast/src/testing/nextjs/app/test/e2e.cy.test.ts
- ast/src/testing/nextjs/app/test/e2e.playwright.each.test.ts
- ast/src/testing/nextjs/app/test/integration.api.spec.ts
- ast/src/testing/nextjs/app/test/mixed.nested.test.ts
- ast/src/testing/nextjs/app/test/param.each.test.ts
- ast/src/testing/nextjs/app/test/puppeteer.flow.test.ts
- ast/src/testing/nextjs/app/test/unit.component.test.tsx
- ast/src/testing/nextjs/mod.rs
> Fix: test coverage fix

- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/mod.rs
- ast/src/lang/queries/react.rs
- ast/src/testing/nextjs/mod.rs
- standalone/src/handlers.rs
- standalone/src/types.rs
> fix: graph inconsistency and fixes

- ast/src/lang/queries/ruby.rs
- ast/src/testing/ruby/mod.rs
- ast/src/testing/ruby/spec/api/api_versioning_spec.rb
- ast/src/testing/ruby/spec/features/country_management_spec.rb
- ast/src/testing/ruby/spec/features/feature_integration_overlap_spec.rb
- ast/src/testing/ruby/spec/features/test_id_lookup_spec.rb
- ast/src/testing/ruby/spec/mixed/nested_classification_spec.rb
- ast/src/testing/ruby/spec/models/article_spec.rb
- ast/src/testing/ruby/spec/models/person_spec.rb
- ast/src/testing/ruby/spec/requests/articles_spec.rb
- ast/src/testing/ruby/spec/services/person_service_spec.rb
- ast/src/testing/ruby/spec/system/js_modal_spec.rb
- ast/src/testing/ruby/spec/system/user_login_spec.rb
- ast/src/testing/ruby/test/integration/countries_test.rb
- ast/src/testing/ruby/test/models/article_test.rb
- ast/src/testing/ruby/test/system/user_flows_test.rb
> feature: ruby tests nodes

- ast/src/lang/graphs/neo4j_utils.rs
- mcp/src/graph/graph.ts
- mcp/src/graph/neo4j.ts
- mcp/src/graph/queries.ts
- mcp/src/graph/routes.ts
- mcp/src/graph/types.ts
- mcp/src/graph/utils.ts
- standalone/src/handlers.rs
Extending /graph endpoint 
Closes #567 #566
> add last modified to node

- mcp/src/eval/tests.ts
- mcp/tests/app.js
- mcp/tests/hooks.js
- mcp/tests/staktrak/dist/playwright-generator.js
- mcp/tests/staktrak/dist/staktrak.js
- mcp/tests/staktrak/src/index.ts
- mcp/tests/staktrak/src/playwright-generator.ts
- mcp/tests/staktrak/src/playwright-replay.ts
- mcp/tests/staktrak/src/types.ts
- mcp/tests/staktrak/src/utils.ts
- mcp/tests/style.css
This PR introduces a new Playwright-based replay functionality that allows users to execute Playwright test code directly in the browser, separate from the existing JSON-based replay system.
- **Test Code Parser**: Extracts executable actions from Playwright test files
- **Browser Execution**: Runs actions directly in the DOM (goto, click, fill, check, etc.)
- **Real-time Progress**: Visual progress tracking with current action display
- **Error Handling**: Robust error handling that continues replay on non-critical failures
- **Toggle Button**: "Show/Hide Code Replay" to reveal Playwright section
- **Code Editor**: Large textarea for pasting Playwright test code
- **Controls**: Start/Pause/Resume/Stop with adjustable speed (0.25x to 3x)
- **Progress Bar**: Purple-themed progress …
> ✨Feature: Implement Playwright Test Text Parsing and Replay

- mcp/package.json
- mcp/src/graph/neo4j.ts
- mcp/src/graph/queries.ts
- mcp/src/graph/routes.ts
- mcp/src/graph/types.ts
- mcp/src/tools/explore/tool.ts
- Figure out the dependency issues for OpenAI and test till it works
- Test and fix Google 
- design a proposal for a more "modular" setup
> fix: setup other models on /explore

- mcp/src/graph/neo4j.ts
- mcp/src/graph/queries.ts
- mcp/src/graph/routes.ts
Test on demo repo: `curl -G 'http://localhost:3000/understanding' --data-urlencode 'question=Detailly, what does this repo achive?' --data-urlencode 'provider=google'`
> fix: use ends with to match name by ending

- ast/src/lang/asg.rs
- ast/src/lang/parse/format.rs
- ast/src/lang/queries/mod.rs
- ast/src/lang/queries/react.rs
> feat:  interface components

- mcp/src/eval/tests.ts
- mcp/tests/staktrak/dist/playwright-generator.js
- mcp/tests/staktrak/dist/replay.js
- mcp/tests/staktrak/dist/staktrak.js
- mcp/tests/staktrak/src/index.ts
- mcp/tests/staktrak/src/playwright-generator.ts
- mcp/tests/staktrak/src/types.ts
- mcp/tests/staktrak/src/utils.ts
This PR implements comprehensive improvements to Playwright test selector generation, delivering semantic, resilient selectors that follow modern Playwright best practices.
**Before (Brittle Selectors):**
```javascript
await page.locator('button.inline-flex.items-center').click();
await page.locator('span').first().click();
```
**After (Semantic Selectors):**
```javascript
await page.getByRole('button', { name: 'Connect Repository' }).click();
await page.locator('header').getByRole('button').first().click();
```
**Enhanced Data Capture:**
- Added comprehensive implicit ARIA role detection for semantic HTML elements
- Implemented semantic parent detection for contextual container identification
- Added icon content detection for SVG/icon font filtering
- Enhanced accessible name resolution …
> Enhanced Playwright selector generation with contextual selection and ARIA role detection

- mcp/tests/app.js
- mcp/tests/hooks.js
- mcp/tests/staktrak/debug_check.js
- mcp/tests/staktrak/dist/playwright-generator.js
- mcp/tests/staktrak/dist/staktrak.js
- mcp/tests/staktrak/src/actions.ts
- mcp/tests/staktrak/src/index.ts
- mcp/tests/staktrak/src/messages.ts
- mcp/tests/staktrak/src/types.ts
- mcp/tests/style.css
- Fixed duplicate action recording in radio button interactions
- Added real-time action broadcasting for all interaction types
- Implemented unified action list with individual removal capability
- Improved TypeScript type safety with message interfaces
- Enhanced UI to always show actions panel toggle
- Verify radio buttons generate single check actions in Playwright tests
- Confirm all action types (clicks, forms, navigation, assertions) appear in real-time list
- Test individual action removal functionality
- Validate type safety with new message interfaces
> Improve StakTrak test generation and action tracking

- ast/src/testing/nextjs/mod.rs
- specifi tests for Unit, integration and e2e tests for sample repo
> test: specific testing for test nature

- ast/src/lang/parse/collect.rs
- ast/src/lang/queries/react.rs
- ast/src/testing/nextjs/app/__tests__/e2e/workspace-settings.spec.ts
- ast/src/testing/nextjs/mod.rs
- standalone/src/handlers.rs
> fix: broken e2e & unit tests 

- ast/src/lang/graphs/neo4j_utils.rs
> fix: query fix

- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- standalone/src/handlers.rs
- standalone/src/main.rs
- standalone/src/types.rs
> fix: test/untested nodes endpoint issue

- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- standalone/src/handlers.rs
- standalone/src/main.rs
Remove test_count from being persisted in the DB
> fix: remove test_count from node

- ast/src/bin/single.rs
- ast/src/lang/parse/format.rs
- ast/src/repo.rs
- lsp/src/language.rs
- mcp/testing/vector-search-response.json
`cargo run --bin single -- path/to/file.ts`
> feat: single file bin setup

- ast/examples/python.rs
- ast/examples/ruby.rs
- ast/examples/url.rs
- ast/src/index.rs
- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/queries/react.rs
- ast/src/repo.rs
- ast/src/testing/graphs/demorepo_test.rs
- ast/src/testing/nextjs/mod.rs
- lsp/src/git.rs
- skill/src/main.rs
- standalone/src/codecov.rs
- standalone/src/handlers.rs
- standalone/src/types.rs
- standalone/tests/fulltest.rs
- standalone/tests/graph_accuracy.rs
- standalone/tests/graph_consistency.rs
- standalone/tests/graph_streaming_consistency.rs
- standalone/tests/graph_updates.rs
> fix: branch to clone param

- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- standalone/src/handlers.rs
- standalone/src/types.rs
> feat: sort by line count and body length

- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/graphs/neo4j_graph.rs
- ast/src/lang/graphs/neo4j_utils.rs
- standalone/src/handlers.rs
- standalone/src/types.rs
> fix: line_coverage and total_lines

- ast/src/lang/parse/collect.rs
- ast/src/lang/queries/ruby.rs
- ast/src/lang/queries/typescript.rs
- ast/src/testing/ruby/mod.rs
> fix: classes in tests files
