- ast/src/lang/queries/react.rs
- ast/src/testing/graphs.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/react/src/ComponentPatterns.tsx
closed: https://github.com/stakwork/stakgraph/issues/93
Unit Test:
> fixed: Capture React Components Defined with `const/export const`

- ast/src/index.rs
- ast/src/lang/graphs/btreemap_graph.rs
- ast/src/utils.rs
Updated the format of `print_json` to output BTreeMapGraph's `jsonl` just like ArrayGraph's
> updated print_json to output like arraygraph

- ast/src/testing/graphs.rs
- lsp/src/language.rs
Added `default_do_lsp` to test for lsp in compare_graphs
> unstuck swift lsp for compare graphs

- mcp/docs/staktrak/README.md
- mcp/docs/staktrak/example-test.spec.js
- mcp/docs/staktrak/frame.html
- mcp/docs/staktrak/playwright-generator.js
- mcp/docs/staktrak/staktrak.js
This PR enhances StakTrak's user interaction recording capabilities by adding support for keyboard input recording and generating more comprehensive Playwright tests. Now users can track not only clicks but also text input in forms, dramatically improving test coverage and automation capabilities.
- Input field recording with data-testid attribute tracking
- Keyboard event capture with detailed context
- Enhanced selector generation for input elements
- Automatic Playwright test generation for form interactions
- Added input field to frame.html with data-testid for reliable selection
- Enhanced keyboard tracking in staktrak.js to store context about input fields
- Added getElementSelector() helper function for robust element identification
- Updated playwright-generator.js to handle …
> Feature: Input field recording and Playwright test generation

- mcp/docs/staktrak/example-test.spec.js
- mcp/docs/staktrak/index.html
- mcp/docs/staktrak/playwright-generator.js
- mcp/docs/staktrak/preact/app.js
- mcp/docs/staktrak/preact/style.css
- mcp/docs/staktrak/staktrak.js
- **Assertion Panel UI**: Added a panel for creating and managing assertions with different types (hasText, containsText, isVisible, hasValue)
- **Text Selection Support**: Implemented selection functionality in the Preact iframe to easily capture text for assertions
- **Assertion Management**: Added UI to display, modify, and remove assertions
- **Playwright Integration**: Updated the test generator to include assertions in chronological order within the test flow
- Added an "Add Assertion" button to the main controls
- Implemented message passing between the parent window and iframe for selection mode
- Enhanced the Preact app to support text selection and element identification
- Added styles for selection state and assertion UI
- Modified the Playwright generator to support different …
> Add Assertion Support to Staktrak Test Recorder

- mcp/docs/staktrak/example-form-elements.spec.js
- mcp/docs/staktrak/index.html
- mcp/docs/staktrak/playwright-generator.js
- mcp/docs/staktrak/preact/app.js
- mcp/docs/staktrak/preact/style.css
- mcp/docs/staktrak/staktrak.js
Adds support for tracking form element interactions (checkboxes, radio buttons, and select dropdowns) and generates appropriate Playwright test commands. Includes new assertion types (isChecked/isNotChecked) and demo UI enhancements to showcase the functionality. This completes the form element tracking feature.
https://www.loom.com/share/1db13831cadd411392c4d918cd28e1b4
> Add form element tracking support (checkboxes, radios, and select dropdowns)

- standalone/tests/graph_updates.rs
The goal is to be able to test `link_api_nodes` during a `sync`
- simulated a new repo at : https://github.com/fayekelmith/graph-update
- updated the content in graph_update to make sure tests still pass
- update the test to test for REQUEST - CALLS -> ENDPOINT
> chore: update graph_update test

- Cargo.lock
- standalone/Cargo.toml
- standalone/src/handlers.rs
- standalone/src/main.rs
- standalone/src/types.rs
Creating asynchronous endpoints for `/sync` and `/ingest` and also a status monitoring endpoint GET `/status/request_id` 
Addressing #410
> feat: standalone async endpoints

- ast/src/lang/queries/java.rs
- ast/src/testing/java/mod.rs
- ast/src/testing/java/src/main/java/graph/stakgraph/java/JavaApplication.java
- ast/src/testing/java/src/main/java/graph/stakgraph/java/controller/PersonController.java
Updated instance queries to pick up Java instances and test them. 
Note: Some instances are from a third-party library, so we'll need to use LSP to obtain the details and construct new edges & nodes.
> fix: java instances

- mcp/src/graph/graph.ts
- mcp/src/graph/neo4j.ts
- mcp/src/graph/queries.ts
- mcp/src/graph/routes.ts
- mcp/src/graph/utils.ts
- mcp/src/tools/stakgraph/get_nodes.ts
- mcp/src/tools/stakgraph/search.ts
This PR adds language filtering capability to the node search functionality. Users can now specify a programming language parameter to filter search results to only include files of that language type.
- Added optional `language` parameter to search and node retrieval methods
- Created `getExtensionsForLanguage()` utility function to map language names to file extensions
- Modified database queries to filter by file extensions at the database level
- Updated all relevant endpoints to pass the language parameter through the call chain
- Ensured backward compatibility with existing code (parameter is optional)
- Graph API (neo4j.ts, queries.ts, graph.ts)
- Node search endpoints
- Search tool schemas
Tested with various language filters:
- JavaScript: filters to .js, .jsx, .cjs, .mjs files
- …
> Add language filtering capability to node search API

- standalone/src/handlers.rs
- standalone/src/types.rs
- Capture the progress
- Return it on the `/ingest_async` endpoint
> feat: capture progress

- mcp/package.json
- mcp/src/graph/routes.ts
- mcp/src/graph/service.ts
- mcp/src/graph/types.ts
- mcp/src/graph/utils.ts
Address #450 
- Clones the repo directly in mcp
- walk through the repo and search for package files using a lightweight library
- use the found pkg_files to get configurations. 
```bash
curl -X GET "http://localhost:3000/services?clone=true&repo_url=https://github.com/stakwork/stakgraph"
curl -X GET "http://localhost:3000/services?clone=true&repo_url=https://github.com/stakwork/demo-repo"
curl -X GET "http://localhost:3000/services?clone=true&repo_url=https://github.com/fayekelmith/FayeKelmith"
```
> improvement: faster of getting service details

- ast/src/lang/queries/angular.rs
- ast/src/lang/queries/react.rs
- ast/src/lang/queries/typescript.rs
- ast/src/testing/react/mod.rs
- ast/src/testing/react/src/App.tsx
- ast/src/testing/react/src/components/Person.tsx
- ast/src/testing/typescript/mod.rs
- ast/src/testing/typescript/src/model.ts
- ast/src/testing/typescript/src/routes.ts
- ast/src/testing/typescript/src/service.ts
Address #455 for Typscritpt, Rust, and Angular. 
updated their queries to capture Enum and Types as DataModels as well.
> fix: enum and types as DataModels for TS based languags

- mcp/src/graph/routes.ts
- mcp/src/graph/types.ts
- mcp/src/graph/utils.ts
The goal is to use a cloned repo, walk through it and use regex expressions to collect all the ENV files used in the code base.
> feat: add envs to /service reponse

- ast/src/testing/nextjs/mod.rs
- lsp/src/git.rs
- lsp/src/utils.rs
- shared/src/error.rs
- standalone/src/types.rs
- standalone/static/app.js
- standalone/static/styles.css
- standalone/static/utils.js
- Propagate errors correctly from the source
- Use the Errors Propagated to Update the UI
- Using the API endpoint to get errors
Addressing #443
> fix: propagate errors to standalone

- Dockerfile.standalone
Build error because of the new crate
> fix:build error from shared

- mcp/tests/staktrak/dist/staktrak.js
- mcp/tests/staktrak/src/debug.ts
Updates Staktrak to use `window.STAKTRAK_CONFIG` instead of Next.js-specific environment variables for React fiber traversal depth configuration.
This makes the library usable in any JavaScript framework (not just Next.js) and allows runtime configuration, which is important for the Hive integration where Staktrak provides DOM debugging capabilities.
Related to stakwork/hive#106
> Make Staktrak library framework-agnostic by using window config instead of Next.js env vars

- ast/src/lang/graphs/graph_ops.rs
- ast/src/lang/linker.rs
- standalone/src/handlers.rs
Currently, the sync uploads a new repository when it's newly added, but does not link API calls. This PR implements a logic to ensure api calls from both graphs are created even when they are ingested at different times.
> fix: update the graph-sync logic

- mcp/package.json
I was getting this error, but only when running from a docker image
```
docker logs b98
node:internal/modules/package_json_reader:255
throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ai-sdk-provider-claude-code' imported from /usr/src/app/build/aieo/src/provider.js
at Object.getPackageJSONURL (node:internal/modules/package_json_reader:255:9)
at packageResolve (node:internal/modules/esm/resolve:767:81)
at moduleResolve (node:internal/modules/esm/resolve:853:18)
at defaultResolve (node:internal/modules/esm/resolve:983:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:783:12)
at #cachedDefaultResolve (node:internal/modules/esm/loader:707:25)
at ModuleLoader.resolve …
```
> depends: adding ai-sdk-provider-claude-code

- mcp/tests/staktrak/dist/staktrak.js
- mcp/tests/staktrak/src/debug.ts
- mcp/tests/staktrak/src/types.ts
- Add getComponentNameFromFiber function to extract component names from React fiber tree
- Support various React patterns: function/class components, ForwardRef, Memo, Lazy, Context
- Format component hierarchy with levels for chat display
- Add ComponentInfo type for component metadata
- Enhance debugMsg to collect and format component information
- Provide fallback messages when no components are detected
> feat: add React component name extraction to DOM inspector

- ast/src/lang/graphs/graph_ops.rs
- standalone/src/handlers.rs
- standalone/src/types.rs
```
pub struct CoverageStat {
pub total: usize, // total nodes (like Functions for unit tests)
pub total_tests: usize, // total test nodes
pub covered: usize,
pub percent: f64,
}
```
Unit Test - CALLS -> Functions
IntegrationTest - CALLS -> Endpoints
E2eTest - CALLS -> Endpoint/Pages
> fix: update coverage statistics

- ast/src/lang/queries/react.rs
- ast/src/testing/nextjs/mod.rs
Removed `describe` from integratin tests 
closes #586
> fix: trim out describe from react/nextjs integration tests

- mcp/tests/hooks.js
- mcp/tests/staktrak/dist/playwright-generator.js
- mcp/tests/staktrak/dist/staktrak.js
- mcp/tests/staktrak/package.json
- mcp/tests/staktrak/src/actionModel.ts
- mcp/tests/staktrak/src/index.ts
- mcp/tests/staktrak/src/playwright-generator.ts
Staktrak generated duplicate `page.fill()` calls for the same input field with the same value. This was caused by a race condition between the debounce timer and blur event handler - both were pushing "complete" input actions independently.
1. **Blur handler fix**: Modified to only push action when debounce timer exists (user blurred before timer fired). If timer doesn't exist, the action was already captured by the debounce completion.
2. **Input deduplication**: Added safety check to remove consecutive duplicate input actions on the same element with the same value, following the existing waitForUrl deduplication pattern.
3. **Build format change**: Changed playwright-generator from ESM to IIFE format to properly expose `window.PlaywrightGenerator` global.
Verified fix eliminates …
> Fix duplicate input actions in Playwright test generation
